title: Pigeoncoin Classic
email: contact@pigeoncoinclassic.org
tagline: Digital freedom
description: >
  Messaging and payments for everyone. Security by Blockchain.

notice:
  show: true
  address: https://play.google.com/store/apps/details?id=org.pgnwallet.aw
  text: Android Mobile Wallet 
  color: has-text-success #danger, warning, success, info, primary, secondary


# config
baseurl: null # baseurl: null # when deployed to pigeoncoinclassic.org

# social links
social:
    Discord: https://discord.gg/Jm977kdqEC
    Twitter: https://twitter.com/Pigeoncoinclassic
    Github: https://github.com/PigeoncoinClassic
    Reddit: https://www.reddit.com/r/Pigeoncoinclassic/
    Telegram: https://t.me/Pigeoncoinclassic
    Medium: https://medium.com/@pigeoncoinclassic

# download links
wallets:
  macOS: https://github.com/PigeoncoinClassic/PigeoncoinClassic/releases/tag/v1.17.01.1
  Windows: https://github.com/PigeoncoinClassic/PigeoncoinClassic/releases/tag/v1.17.01.1
  Linux: https://github.com/PigeoncoinClassic/PigeoncoinClassic/releases/tag/v1.17.01.1
  Android: https://play.google.com/store/apps/details?id=org.pgnwallet.aw

miners:
  Nvidia: https://github.com/Pigeoncoin/ccminer
  AMD: https://github.com/andru-kun/wildrig-multi/releases/

exchanges:
  'AUTRADEX': https://autradex.systems

broadcasts:
  
pool:
  website: https://cminors-pool.com/
  address: https://cminors-pool.com/

explorer:
  website: https://openchains.info

donate:
   pgc: PF6ZtE2YjUK2328JeyJBbbWGRiH8Hydoqj
#  pgn: PDiZ89gk5HMqwrcGp6Hs9WdgFALzLbD4HG
#  btc: 1NaVP4cKiWY6MxSDkTCZ2kh5Xm3coA27Qv

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# collections:
# - roadmap

sass:
  sass_dir: _sass
  style: compressed


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
